import Head from 'next/head';
import { useRef } from 'react';
import styles from 'styles/Home.module.css';

export default function Home() {
  const inputRef = useRef<HTMLInputElement>(null);

  const handleClick = () => {
    const name = inputRef.current.value.trim();
    if (!name) {
      alert('name을 입력 하세요');
      return;
    }

    const searchParam = new URLSearchParams();
    searchParam.append('name', name);
    fetch(`/api/add-item?${searchParam.toString()}`)
      .then((res) => res.json())
      .then((json) => alert(json.message));
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <button onClick={handleClick}>등록하기</button>
          <input ref={inputRef} type="text" />
        </div>
      </main>
    </>
  );
}
